### ISSUE TITLE
swagger generation issue

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Tags#4]
Error: https://github.com/EscolaLMS/Tags/runs/2440021065?check_suite_focus=true

`Required @OA\Info() not found` can be resolved by the following 

![image](https://user-images.githubusercontent.com/214608/116113871-30092b80-a6b9-11eb-91cd-c01b92df5b74.png)

Copy solution from 

* https://github.com/EscolaLMS/H5P/blob/main/.github/workflows/swagger.yml#L22
* https://github.com/EscolaLMS/H5P/blob/main/src/HeadlessH5PServiceProvider.php#L31

**Comment by HerbertIV** [comment]
Add versioner for tags package
